### ISSUE TITLE
C# sample does not include instructions to demonstrate use Scans tab on build results page

### ISSUE THREAD

**Issue by adarshrema** [microsoft/axe-pipelines-samples#155]
## Update following sections of the C# sample to be inline with the typescript sample,
* Getting started
  * samplepagetests.cs to include instructions to use axe-sarif-converter to convert axe results to sarif format
  * azure-pipelines.yml to add Publish Build Artifacts task to paint the Scans tab
* Tools and libraries used
  * axe-sarif-converter to convert axe results to SARIF format
  * **Sarif Viewer Build Tab** to visualize the results in Azure Pipelines
* See it in action on Azure Pipelines
  * Reference to **Sarif Viewer Build Tab**
  * Screenshot of Scans tab in sample build
  * Link (off the screenshot) to the live demo of Scans tab on sample build

**Comment by deep-mm** [comment]
Any updates on this on how to display output of C# sample in Scans tab?

**Comment by deep-mm** [comment]
I was able to find a way to do this for C# Selenium with the help of axe sarif convertor.
Use .WithOutputFile to export the axe results as a json file, we will use this json file as an input to axe-sarif-converter and get a sarif file as output

**In the Selenium Tests code:**
```
 axeResult = new AxeBuilder(driver)
                            .WithTags("wcag2a","wcag2aa") //Can mention more tags like wcag2aa, wcag21a..
                            .WithOutputFile(testResultPath + "BeforeLoginTest.json")
                            .Analyze(); //Leave it blank to analyze whole page or enter a webelement to analyze that particular element 
```

*testResultPath can be any path as required (Store in appsettings.test.json, and access from there)
*Accessibility-Test-Result-Path is the path where we want to export the json files

**In the Azure Pipeline:**

**---Update the Test Result Path in appsetting.test.json---**
```
- task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $configPath = "$(Build.SourcesDirectory)/web/appsettings.test.json"
                Write-Output "Loading appsettings file from $configPath"
                $json = Get-Content $configPath | ConvertFrom-Json
                $json.TestResultsPath = '$(Accessibility-Test-Result-Path)'
                Write-Output "Updating the file to make the changes"
                $json | ConvertTo-Json -depth 32| set-content $configPath
```

**---Run VS Tests---**
```
- task: VSTest@2
  displayName: Run Accessibility Tests
  inputs:
testSelector: 'testAssemblies'
testAssemblyVer2: |
                **\*ui.tests*.dll
                !**\*TestAdapter.dll
                !**\obj\**
searchFolder: '$(Build.SourcesDirectory)/web'
testFiltercriteria: 'TestCategory=AccessibilityTests'
uiTests: true
continueOnError: true
```

**---Run a Powershell Script to convert json output to sarif---**
          ```
- task: PowerShell@2
            displayName: 'Convert AXE to Sarif'
            inputs:
              targetType: 'inline'
              script: |
                npx axe-sarif-converter --input-files $(Accessibility-Test-Results)BeforeLoginTest.json --output-file $(Accessibility-Test-Result-Path)BeforeLoginTest.sarif --force
            continueOnError: true
```



**---Publish the Sarif Output Files to CodeAnalysisLogs Artifact to allow the Sarif extension to read those---**
      ```
    - task: PublishBuildArtifacts@1
            displayName: publish accessibility test results
            inputs:
              # The exact name "CodeAnalysisLogs" is required for the Sarif Results Viewer Extension for Azure Pipelines
              # to find the .sarif files our accessibility test produces.
              artifactName: 'CodeAnalysisLogs'
              # "test-results" is not a required convention; it just happens to be where our tests write .sarif files to.
              pathtoPublish: '$(Accessibility-Test-Result-Path)' 

```
